version: "3.8"

services:
  app:
    build: .
    container_name: devops-app
    environment:
      - PORT=3001
    expose:
      - "3001"

  nginx:
    image: nginx:latest
    container_name: devops-nginx
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
